name: Auto Push to Server

on:
  push:
    branches:
      - master
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install -g pnpm && pnpm install  --no-frozen-lockfile
      - name: Build
        run: pnpm build
      - name: debug
        run: ls 
      # - name: deploy to github-page
      #   uses: s0/git-publish-subdir-action@develop
      #   env:
      #     REPO: git@github.com:Agiantii/Agiantii.github.io.git
      #     BRANCH: gh-pages
      #     FOLDER: dist
      #     SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "./dist" # 直接把dist传到服务器 
          target: ${{ secrets.TARGET }}